name: Telemetric Demo FE Deployment

on:
  push:
    branches: [ "main" ]

jobs:

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Create environment production and build
        run: |
          echo "${{ secrets.ENV_FILE_PRODUCTION }}" > .env.production
          npm install
          npm run build
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: sigitnurmajid/telemetric-demo-fe
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  pull_the_registery:
    needs: push_to_registry
    name: Push Docker image to Server
    runs-on: ubuntu-latest

    steps:  
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          sudo docker stop telemetric-demo-fe
          sudo docker rm telemetric-demo-fe

          sudo docker rmi sigitnurmajid/telemetric-demo-fe:main
          sudo docker pull sigitnurmajid/telemetric-demo-fe:main

          docker run -d -p 8080:80 --name telemetric-demo-fe sigitnurmajid/telemetric-demo-fe:main
